apiVersion: v1
name: monocular
description: Monocular is a search and discovery front end for Helm Charts Repositories.
version: 0.6.5
appVersion: v1.0.0
home: https://github.com/helm/monocular
sources:
- https://github.com/helm/monocular
maintainers:
- name: prydonius
  email: adnan@bitnami.com
