swagger: "2.0"
info:
  title: Monocular
  version: 0.0.1
produces:
  - application/json
consumes:
  - application/json
schemes:
  - http
paths:
  /healthz:
    get:
      operationId: healthz
      summary: "health check"
      responses:
        200:
          description: healthy
        default:
          description: unexpected error
  /v1/charts/{repo}/{chartName}:
    get:
      operationId: getChart
      summary: "get chart by repo/name"
      parameters:
        - name: repo
          in: path
          type: string
          required: true
        - name: chartName
          in: path
          type: string
          required: true
      responses:
        200:
          description: chart response
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/resource"
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/error"
definitions:
  resource:
    type: object
    required:
      - type
      - id
      - attributes
    properties:
      type:
        type: string
        minLength: 1
      id:
        type: string
        minLength: 1
      links:
        type: object
      attributes:
        type: object
  chartVersion:
    type: object
    required:
      - name
      - url
      - created
      - checksum
      - description
      - version
      - home
    properties:
      name:
        type: string
        minLength: 1
      url:
        type: string
        minLength: 1
      created:
        type: string
        minLength: 1
      checksum:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1
      version:
        type: string
        minLength: 1
      home:
        type: string
        minLength: 1
  chartResourceLinks:
    type: object
    required:
      - latest
      - home
    properties:
      latest:
        type: string
        minLength: 1
      home:
        type: string
        minLength: 1
  chartResourceAttributes:
    type: object
    required:
      - name
      - description
      - created
      - checksum
    properties:
      name:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1
      created:
        type: string
        minLength: 1
  error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
